# Generated by Django 6.0.1 on 2026-01-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_driver_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Машины дугаар'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Овог'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Идэвхтэй'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Нэр'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Утасны дугаар'),
        ),
    ]
